name: Install Rails Installer
on:
  push:
    branches:
      - github-action
  pull_request:
    branches:
      - github-action

jobs:
  install:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rails Installer test
        run: |
          $url = 'https://github.com/railsinstaller/railsinstaller-windows/releases/download/v4.0.1/railsinstaller-4.0.1.exe'
          $output = "$env:TEMP\railsinstaller-4.0.1.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList '/silent' -Wait
