name: Install Rails Installer
on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - github-actions

jobs:
  install:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rails Installer
        run: |
          $url = 'https://github.com/railsinstaller/railsinstaller-windows/releases/download/v4.0.1/railsinstaller-4.0.1.exe'
          $output = "$env:TEMP\railsinstaller-4.0.1.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList '/silent' -Wait
          
          
          $url = 'https://github.com/railsinstaller/railsinstaller-windows/releases/download/v4.0.1/railsinstaller-4.0.1.exe'
          $output = "$env:TEMP\railsinstaller-4.0.1.exe"
          Invoke-WebRequest -Uri $url -OutFile $output

          # Run the Rails Installer executable with silent mode
          Start-Process -FilePath $output -ArgumentList '/silent' -Wait

          # Verify the installation
          $installDir = "C:\RailsInstaller"
          if (Test-Path $installDir) {
            Write-Host "Rails Installer installed successfully."
          } else {
            Write-Host "Rails Installer installation failed."
          }
      
      - name: Check Ruby version
        run: |
          ruby -v
          
      - name: Check Rails version
        run: |
          rails -v